/** Zingro Homemaker design tokens (ported from Stitch DESIGN.md) */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#fcf9f8",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#ebe6e4",
        "surface-container-high": "#e0dbd9",
        "surface-container-highest": "#f2e4dc",
        "surface-variant": "#f2e4dc",
        "inverse-surface": "#2a313d",
        "inverse-on-surface": "#ebf1ff",
        "on-surface": "#151c27",
        "on-surface-variant": "#3d4a42",
        outline: "#85736b",
        "outline-variant": "#d5c3ba",
        background: "#fcf9f8",
        "on-background": "#151c27",
        primary: "#ff6b00",
        "on-primary": "#ffffff",
        "primary-container": "#ff6b00",
        "on-primary-container": "#4b1600",
        "primary-fixed": "#ffdbc7",
        "primary-fixed-dim": "#ffb68d",
        "on-primary-fixed": "#310e00",
        "on-primary-fixed-variant": "#923700",
        "inverse-primary": "#ffb68d",
        "surface-tint": "#ff6b00",
        secondary: "#0051d5",
        "on-secondary": "#ffffff",
        "secondary-container": "#316bf3",
        "on-secondary-container": "#fefcff",
        "secondary-fixed": "#dbe1ff",
        "secondary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed": "#00174b",
        "on-secondary-fixed-variant": "#003ea8",
        tertiary: "#9b3e3b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ba5551",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffdad7",
        "tertiary-fixed-dim": "#ffb3ae",
        "on-tertiary-fixed": "#410004",
        "on-tertiary-fixed-variant": "#7f2928",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", "2xl": "1rem", full: "9999px" },
      spacing: {
        gutter: "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "margin-mobile": "20px",
        "touch-target-min": "48px",
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-lg": ["Noto Sans", "sans-serif"],
        "label-sm": ["Noto Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      boxShadow: {
        card: "0 2px 8px rgba(0,0,0,0.05)",
        modal: "0 4px 12px rgba(0,0,0,0.10)",
      },
    },
  },
  plugins: [],
};
